### ISSUE TITLE
打开报错呀

### ISSUE THREAD

**Issue by h824612113** [FingerCaster/StarForce-ILRuntime#1]
![image](https://user-images.githubusercontent.com/18304525/165906349-f23227e9-d079-49f1-ae34-a62f904c0e13.png)
这是unity的，
![image](https://user-images.githubusercontent.com/18304525/165906373-58c1724f-69ab-4e96-936d-224edef96084.png)
zhes这是rider的，我用的unity是2019.4.29，rider是2021的

**Comment by FingerCaster** [comment]
宏的问题 你可以自己看代码加一下
